name: Site Deployment - Production 🚀

on:
  push:
    branches:
          - main
    paths:
      - docs/**

jobs:
  publish-production-site:
  environment: 'site-production'
    uses: ./.github/workflows/service_deploy-static-site.yml
    secrets: inherit